name: Deploy API to EC2

on:
  push:
    branches:
      - master
    # (optional) only run when files in /api change:
    paths:
      - 'api/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Install & build **only** the API
      - name: Install dependencies & build API
        working-directory: api
        run: |
          npm ci
          npm run build   # if you have a build step

      - name: Sync & reload API on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            cd /srv/my-node-app   # this is your monorepo root on the server
            git fetch --all
            git reset --hard origin/master
            # now install just the API and reload it
            cd api
            npm ci
            pm2 reload ../ecosystem.config.js --env production
