services:
  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   restart: unless-stopped
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis-data:/data

  app:
    build: .
    ports:
      - "3010:3010"  
    volumes:
      - .:/src             
      - ./node_modules:/src/node_modules
    depends_on:
      - postgres
    environment:
      API_PORT: ${API_PORT}
      PG_TYPE: ${PG_TYPE}
      PG_PORT: ${PG_PORT}
      HOST: ${HOST}
      DB_USER: ${DB_USER}
      DATABASE: ${DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      WHATSAPP_TOKEN: ${WHATSAPP_TOKEN}
      WHATSAPP_VERIFY_TOKEN: ${WHATSAPP_VERIFY_TOKEN}
      WHATSAPP_PHONE_NUMBER_ID: ${WHATSAPP_PHONE_NUMBER_ID}

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - expenses-app-pg-data:/var/lib/postgresql/data

volumes:
  expenses-app-pg-data: