name: Deploy API to EC2

concurrency:
  group: deploy-api
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & build API
        working-directory: api
        run: |
          npm ci
          npm run build

      - name: Sync dist folder to EC2
        uses: burnett01/rsync-deployments@7.0.2
        with:
          switches: -avz --delete
          path: api/dist/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: /home/ubuntu/repo/expenses-app/api/dist

      - name: Reload PM2 on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # ensure we’re using your ecosystem file
            pm2 startOrReload /home/ubuntu/repo/expenses-app/ecosystem.config.js --env production
