name: Deploy API to EC2

concurrency:
  group: deploy-api
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    # (optional) only run when files in /api change:
    paths:
      - 'api/**'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build API on runner
        working-directory: api
        run: |
          npm ci
          npm run build
      - name: Sync API to EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /home/ubuntu/repo/expenses-app/api
            mkdir -p releases
      - name: Rsync dist folder
        uses: burnett01/rsync-deployments@v4
        with:
          switches: -avz --delete
          path: api/dist/
          remote_host: ${{ secrets.EC2_HOST }}
          remote_user: ${{ secrets.EC2_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: /home/ubuntu/repo/expenses-app/api/dist
      - name: Reload PM2 on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            pm2 reload /home/ubuntu/repo/expenses-app/ecosystem.config.js --env production
